export interface SupportTopic {
  id: string;
  label: string;
  scopeSummary: string;
  keywords: string[];
  antiKeywords: string[];
  allowedExamples: string[];
  refusalScript: string;
}

export const SUPPORT_TOPICS: SupportTopic[] = [
  {
    id: "hotel",
    label: "Hotel Support",
    scopeSummary:
      "any hotel and guest support question in any wording: stays, bookings, check-in, check-out, rooms, amenities, housekeeping, billing, policies, spa, parking, and special requests",
    keywords: [
      "hotel",
      "guest",
      "room",
      "check-in",
      "check in",
      "checkout",
      "check-out",
      "reservation",
      "booking",
      "housekeeping",
      "amenities",
      "reception",
      "concierge",
      "stay",
      "suite",
      "lobby",
      "wifi",
      "breakfast",
      "late checkout",
      "parking",
      "pool",
      "towels",
      "folio",
      "bill",
      "upgrade",
      "minibar",
      "spa",
      "valet",
      "laundry",
      "noise",
      "help",
    ],
    antiKeywords: [
      "recipe",
      "cook",
      "ingredient",
      "flight",
      "airline",
      "airport",
      "password reset",
      "laptop",
      "loan",
      "credit card",
      "mortgage",
      "order number",
      "ecommerce",
      "shopping cart",
      "return policy online",
    ],
    allowedExamples: [
      "What time is check-in?",
      "Can I get a late checkout?",
      "Is there a gym and what are the hours?",
      "I need extra towels and a quiet room.",
    ],
    refusalScript:
      "I can only help with hotel and guest support questions in this line. Please change the Support topic in Settings if you need a different department, then start a new conversation.",
  },
  {
    id: "cooking",
    label: "Cooking",
    scopeSummary:
      "any cooking question: recipes for any dish, spices and masalas, ingredients and substitutions, techniques, timing, and food safety — in any phrasing the user uses",
    keywords: [
      "recipe",
      "recipes",
      "cook",
      "cooking",
      "make",
      "prepare",
      "how to",
      "bake",
      "fry",
      "boil",
      "grill",
      "roast",
      "simmer",
      "ingredient",
      "kitchen",
      "meal",
      "dish",
      "food",
      "eat",
      "spice",
      "spices",
      "masala",
      "turmeric",
      "cumin",
      "coriander",
      "chili",
      "garam",
      "temper",
      "tadka",
      "oven",
      "stove",
      "sauce",
      "soup",
      "salad",
      "cake",
      "bread",
      "rice",
      "pasta",
      "curry",
      "biryani",
      "dal",
      "omelette",
      "smoothie",
      "vegetarian",
      "vegan",
      "gluten",
      "substitute",
      "pav bhaji",
      "chicken",
      "paneer",
    ],
    antiKeywords: [
      "hotel",
      "check-in",
      "reservation",
      "flight",
      "airline",
      "boarding pass",
      "password",
      "vpn",
      "loan",
      "bank account",
      "order tracking",
      "refund shipping",
      "warehouse",
    ],
    allowedExamples: [
      "How do I make pav bhaji?",
      "What is turmeric used for in cooking?",
      "How do I temper mustard seeds?",
      "What can I substitute for cream?",
    ],
    refusalScript:
      "I only help with cooking — recipes, spices, ingredients, and techniques — on this line. Change the Support topic in Settings for hotel, travel, banking, or other help, then start a new conversation.",
  },
  {
    id: "retail",
    label: "Retail Support",
    scopeSummary:
      "any online shopping and retail question in any wording: orders, tracking, shipping, delivery, returns, refunds, products, sizes, promos, warranty, payment issues, and order problems",
    keywords: [
      "order",
      "orders",
      "shipping",
      "ship",
      "delivery",
      "deliver",
      "return",
      "refund",
      "exchange",
      "tracking",
      "track",
      "package",
      "product",
      "item",
      "size",
      "promo",
      "discount",
      "coupon",
      "cart",
      "checkout",
      "warehouse",
      "damaged",
      "wrong",
      "missing",
      "payment",
      "warranty",
      "subscription",
      "gift card",
      "pickup",
      "help",
    ],
    antiKeywords: [
      "hotel",
      "room service",
      "recipe",
      "ingredient",
      "flight",
      "gate",
      "boarding",
      "mortgage",
      "interest rate",
      "virus",
      "laptop driver",
    ],
    allowedExamples: [
      "Where is my order?",
      "How do I return an item?",
      "Can I use a gift card with a promo code?",
      "Can I change the shipping address?",
    ],
    refusalScript:
      "This line is for retail and online shopping support only. Pick another Support topic in Settings if you need hotel, cooking, or travel help.",
  },
  {
    id: "travel",
    label: "Travel Support",
    scopeSummary:
      "any travel and airline question in any wording: flights, bookings, changes, delays, baggage, seats, airports, visas, lounges, connections, and trip issues",
    keywords: [
      "flight",
      "flights",
      "airline",
      "airport",
      "baggage",
      "luggage",
      "bag",
      "boarding",
      "gate",
      "itinerary",
      "ticket",
      "seat",
      "delay",
      "delayed",
      "cancel",
      "cancellation",
      "passport",
      "visa",
      "trip",
      "travel",
      "fly",
      "connection",
      "lounge",
      "tsa",
      "rental car",
      "hotel booking",
      "help",
    ],
    antiKeywords: [
      "recipe",
      "cook",
      "ingredient",
      "room service",
      "housekeeping",
      "check-in hotel",
      "password reset",
      "printer",
      "loan application",
      "return item damaged",
    ],
    allowedExamples: [
      "How do I change my flight?",
      "What is the baggage allowance?",
      "Do I need a visa for this trip?",
      "My flight was delayed — what are my options?",
    ],
    refusalScript:
      "I can only discuss travel and airline topics here. Change Support topic in Settings for cooking, hotel, or retail questions.",
  },
  {
    id: "banking",
    label: "Banking Support",
    scopeSummary:
      "any banking question in any wording: accounts, cards, loans, rates, repo rate, transfers, UPI, NEFT, RTGS, KYC, fees, fraud, statements, fixed deposits, branches, ATMs, PIN, and general money-banking topics — demo guidance only, not real financial advice",
    keywords: [
      "bank",
      "banking",
      "account",
      "accounts",
      "balance",
      "transfer",
      "transaction",
      "debit",
      "credit",
      "card",
      "loan",
      "mortgage",
      "statement",
      "branch",
      "atm",
      "pin",
      "overdraft",
      "savings",
      "checking",
      "deposit",
      "fee",
      "rate",
      "rates",
      "repo",
      "interest",
      "apy",
      "emi",
      "upi",
      "neft",
      "rtgs",
      "imps",
      "kyc",
      "cheque",
      "check",
      "fd",
      "fixed deposit",
      "forex",
      "swift",
      "fraud",
      "ifsc",
      "micr",
      "cibil",
      "credit score",
      "help",
    ],
    antiKeywords: [
      "recipe",
      "hotel room",
      "flight",
      "boarding",
      "return package",
      "shipping label",
      "install software",
      "wifi router",
    ],
    allowedExamples: [
      "How do I reset my banking PIN in demo mode?",
      "What is the repo rate?",
      "How does UPI work?",
      "What documents do I need to open an account?",
    ],
    refusalScript:
      "This demo line only covers banking topics. For hotel, travel, cooking, or shopping help, change Support topic in Settings.",
  },
  {
    id: "it_helpdesk",
    label: "IT Helpdesk",
    scopeSummary:
      "any workplace IT help question in any wording: passwords, login, email, VPN, Wi-Fi, software, installs, printers, laptops, phones, MFA, errors, and access",
    keywords: [
      "password",
      "login",
      "log in",
      "vpn",
      "email",
      "outlook",
      "teams",
      "laptop",
      "computer",
      "printer",
      "print",
      "wifi",
      "network",
      "internet",
      "software",
      "install",
      "update",
      "driver",
      "access",
      "locked",
      "error",
      "crash",
      "slow",
      "help",
      "tech",
      "support",
      "mfa",
      "two-factor",
      "chrome",
      "zoom",
      "slack",
      "monitor",
      "phone",
    ],
    antiKeywords: [
      "recipe",
      "ingredient",
      "hotel",
      "check-in",
      "flight",
      "baggage",
      "refund order",
      "shipping",
      "loan rate",
      "mortgage",
    ],
    allowedExamples: [
      "I cannot connect to the VPN.",
      "How do I reset my work password?",
      "How do I set up MFA on my phone?",
      "My laptop will not print.",
    ],
    refusalScript:
      "I only handle IT helpdesk questions on this line. Change Support topic in Settings for other departments.",
  },
];

export const DEFAULT_TOPIC_ID = "hotel";

const topicById = new Map(SUPPORT_TOPICS.map((topic) => [topic.id, topic]));

export function getTopic(topicId: string): SupportTopic | undefined {
  return topicById.get(topicId);
}

export function isValidTopicId(topicId: string): boolean {
  return topicById.has(topicId);
}
